"""ordered execution traces

Revision ID: 0fe7f845cf6f
Revises: 0b3e65b38568
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0fe7f845cf6f"
down_revision: str | None = "0b3e65b38568"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    replace_case_status(include_completed=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_events",
        sa.Column("case_result_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_execution_events_payload_object")
        ),
        sa.CheckConstraint(
            "kind IN ('case_started', 'model_request', 'model_response', 'model_error', "
            "'tool_request', 'tool_result', 'error', 'case_completed')",
            name=op.f("ck_execution_events_kind_supported"),
        ),
        sa.CheckConstraint(
            "finished_at >= started_at", name=op.f("ck_execution_events_timestamp_order")
        ),
        sa.CheckConstraint(
            "input_tokens IS NULL OR input_tokens >= 0",
            name=op.f("ck_execution_events_input_tokens_nonnegative"),
        ),
        sa.CheckConstraint("latency_ms >= 0", name=op.f("ck_execution_events_latency_nonnegative")),
        sa.CheckConstraint(
            "output_tokens IS NULL OR output_tokens >= 0",
            name=op.f("ck_execution_events_output_tokens_nonnegative"),
        ),
        sa.CheckConstraint("sequence >= 0", name=op.f("ck_execution_events_sequence_nonnegative")),
        sa.CheckConstraint(
            "total_tokens IS NULL OR total_tokens >= 0",
            name=op.f("ck_execution_events_total_tokens_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["case_result_id"],
            ["case_results.id"],
            name=op.f("fk_execution_events_case_result_id_case_results"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_events")),
        sa.UniqueConstraint(
            "case_result_id", "sequence", name=op.f("uq_execution_events_case_result_id")
        ),
    )
    op.create_index(
        op.f("ix_execution_events_case_result_id"),
        "execution_events",
        ["case_result_id"],
        unique=False,
    )
    op.add_column(
        "case_results",
        sa.Column(
            "input_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("case_results", sa.Column("provider", sa.String(length=30), nullable=True))
    op.add_column("case_results", sa.Column("model_name", sa.String(length=200), nullable=True))
    op.add_column("case_results", sa.Column("latency_ms", sa.Float(), nullable=True))
    op.add_column("case_results", sa.Column("input_tokens", sa.Integer(), nullable=True))
    op.add_column("case_results", sa.Column("output_tokens", sa.Integer(), nullable=True))
    op.add_column("case_results", sa.Column("total_tokens", sa.Integer(), nullable=True))
    op.add_column("case_results", sa.Column("error_type", sa.String(length=60), nullable=True))
    op.add_column("tool_calls", sa.Column("error_type", sa.String(length=60), nullable=True))
    op.add_column(
        "tool_calls",
        sa.Column("arguments_validated", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column("tool_calls", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tool_calls", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tool_calls", sa.Column("latency_ms", sa.Float(), nullable=True))
    for column in ("input_tokens", "output_tokens", "total_tokens"):
        op.create_check_constraint(
            f"{column}_nonnegative", "case_results", f"{column} IS NULL OR {column} >= 0"
        )
    for table in ("case_results", "tool_calls"):
        op.create_check_constraint(
            "latency_nonnegative", table, "latency_ms IS NULL OR latency_ms >= 0"
        )
    op.create_check_constraint(
        "timestamp_order", "tool_calls", "finished_at IS NULL OR finished_at >= started_at"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Old schema lacks an unscored completion state; preserve terminal success as passed.
    replace_case_status(include_completed=False)
    for column in ("input_tokens", "output_tokens", "total_tokens"):
        op.drop_constraint(
            op.f(f"ck_case_results_{column}_nonnegative"), "case_results", type_="check"
        )
    for table in ("case_results", "tool_calls"):
        op.drop_constraint(op.f(f"ck_{table}_latency_nonnegative"), table, type_="check")
    op.drop_constraint(op.f("ck_tool_calls_timestamp_order"), "tool_calls", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tool_calls", "latency_ms")
    op.drop_column("tool_calls", "finished_at")
    op.drop_column("tool_calls", "started_at")
    op.drop_column("tool_calls", "arguments_validated")
    op.drop_column("tool_calls", "error_type")
    op.drop_column("case_results", "error_type")
    op.drop_column("case_results", "total_tokens")
    op.drop_column("case_results", "output_tokens")
    op.drop_column("case_results", "input_tokens")
    op.drop_column("case_results", "latency_ms")
    op.drop_column("case_results", "model_name")
    op.drop_column("case_results", "provider")
    op.drop_column("case_results", "input_snapshot")
    op.drop_index(op.f("ix_execution_events_case_result_id"), table_name="execution_events")
    op.drop_table("execution_events")
    # ### end Alembic commands ###


def replace_case_status(*, include_completed: bool) -> None:
    # Rebuild transactionally so upgrades also work inside isolated test schemas.
    op.execute("ALTER TABLE case_results ALTER COLUMN status DROP DEFAULT")
    op.execute("ALTER TYPE case_status RENAME TO case_status_previous")
    values = ["pending", "running", "passed", "failed", "error", "skipped"]
    if include_completed:
        values.insert(2, "completed")
    sa.Enum(*values, name="case_status").create(op.get_bind())
    expression = (
        "status::text"
        if include_completed
        else ("CASE WHEN status::text = 'completed' THEN 'passed' ELSE status::text END")
    )
    op.execute(
        f"ALTER TABLE case_results ALTER COLUMN status TYPE case_status "
        f"USING ({expression})::case_status"
    )
    op.execute("ALTER TABLE case_results ALTER COLUMN status SET DEFAULT 'pending'::case_status")
    op.execute("DROP TYPE case_status_previous")
